/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package datasiswa202457201050;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author binak
 */
public class Jurusan extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Jurusan() {
        initComponents();
    }

    void tampil_tb_jurusan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("kode jurusan");
        model.addColumn("nama jurusan");

        try {
            String sql = "SELECT * FROM jurusan";
            java.sql.Connection conn = Koneksi.konek();
            java.sql.Statement statement = conn.createStatement();
            java.sql.ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                model.addRow(new Object[]{resultSet.getString("kode_jur"), resultSet.getString("nama_jurusan")});
            }
            tb_jurusan.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void reset() {
        tf_KodeJurusan.setText(null);
        tf_NamaJurusan.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_txtDataJurusan = new javax.swing.JLabel();
        tf_KodeJurusan = new javax.swing.JTextField();
        tf_NamaJurusan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_TambahDataJurusan = new javax.swing.JToggleButton();
        btn_UbahDataJurusan = new javax.swing.JToggleButton();
        btn_HapusDataJurusan = new javax.swing.JToggleButton();
        btn_ResetDataJurusan = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_jurusan = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        lb_txtDataJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_txtDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        lb_txtDataJurusan.setText("Data Jurusan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_txtDataJurusan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_txtDataJurusan)
                .addContainerGap())
        );

        tf_KodeJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_KodeJurusanActionPerformed(evt);
            }
        });

        tf_NamaJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NamaJurusanActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Jurusan");

        jLabel2.setText("Kode Jurusan");

        btn_TambahDataJurusan.setBackground(new java.awt.Color(0, 153, 0));
        btn_TambahDataJurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_TambahDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btn_TambahDataJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-add-20.png"))); // NOI18N
        btn_TambahDataJurusan.setText("Tambah");
        btn_TambahDataJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahDataJurusanActionPerformed(evt);
            }
        });

        btn_UbahDataJurusan.setBackground(new java.awt.Color(255, 153, 0));
        btn_UbahDataJurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_UbahDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btn_UbahDataJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-write-20.png"))); // NOI18N
        btn_UbahDataJurusan.setText("Ubah");
        btn_UbahDataJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahDataJurusanActionPerformed(evt);
            }
        });

        btn_HapusDataJurusan.setBackground(new java.awt.Color(204, 0, 0));
        btn_HapusDataJurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_HapusDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btn_HapusDataJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-delete-20.png"))); // NOI18N
        btn_HapusDataJurusan.setText("Hapus");
        btn_HapusDataJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusDataJurusanActionPerformed(evt);
            }
        });

        btn_ResetDataJurusan.setBackground(new java.awt.Color(0, 153, 255));
        btn_ResetDataJurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ResetDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ResetDataJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-reset-20 .png"))); // NOI18N
        btn_ResetDataJurusan.setText("Reset");
        btn_ResetDataJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetDataJurusanActionPerformed(evt);
            }
        });

        tb_jurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_jurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_jurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_jurusan);

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_KodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(tf_NamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addComponent(btn_TambahDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_UbahDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_HapusDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ResetDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_KodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TambahDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UbahDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HapusDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ResetDataJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(pn_dasar, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tf_KodeJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_KodeJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_KodeJurusanActionPerformed

    private void tf_NamaJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NamaJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NamaJurusanActionPerformed

    private void btn_TambahDataJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahDataJurusanActionPerformed
        String kode = tf_KodeJurusan.getText();
        String nama = tf_NamaJurusan.getText();
        try {
            String sql = "INSERT INTO jurusan(kode_jur,nama_jurusan)VALUES('" + kode + "','" + nama + "')";
            java.sql.Connection conn = Koneksi.konek();
            java.sql.Statement statement = conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampil_tb_jurusan();
        reset();
    }//GEN-LAST:event_btn_TambahDataJurusanActionPerformed

    private void btn_UbahDataJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahDataJurusanActionPerformed
        String kode = tf_KodeJurusan.getText();
        String nama = tf_NamaJurusan.getText();
        try {
            String sql = "UPDATE jurusan SET nama_jurusan= '" + nama + "'WHERE kode_jur='" + kode + "'";
            java.sql.Connection conn = Koneksi.konek();
            java.sql.Statement statement = conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampil_tb_jurusan();
        reset();
    }//GEN-LAST:event_btn_UbahDataJurusanActionPerformed

    private void btn_HapusDataJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusDataJurusanActionPerformed
        String kode_jur = tf_KodeJurusan.getText();
        try {
            String sql = "DELETE FROM jurusan WHERE kode_jur='" + kode_jur + "'";
            java.sql.Connection conn = Koneksi.konek();
            java.sql.Statement statement = conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampil_tb_jurusan();
        reset();
    }//GEN-LAST:event_btn_HapusDataJurusanActionPerformed

    private void btn_ResetDataJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetDataJurusanActionPerformed
        reset();
    }//GEN-LAST:event_btn_ResetDataJurusanActionPerformed

    private void tb_jurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_jurusanMouseClicked
        int baris =tb_jurusan.rowAtPoint(evt.getPoint());
        String kode=tb_jurusan.getValueAt(baris,0).toString();
        String nama=tb_jurusan.getValueAt(baris,1).toString();
        tf_KodeJurusan.setText(kode);
        tf_NamaJurusan.setText(nama);
        tf_KodeJurusan.setEditable(false);
    }//GEN-LAST:event_tb_jurusanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_HapusDataJurusan;
    private javax.swing.JToggleButton btn_ResetDataJurusan;
    private javax.swing.JToggleButton btn_TambahDataJurusan;
    private javax.swing.JToggleButton btn_UbahDataJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_txtDataJurusan;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JTable tb_jurusan;
    private javax.swing.JTextField tf_KodeJurusan;
    private javax.swing.JTextField tf_NamaJurusan;
    // End of variables declaration//GEN-END:variables
}
