/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datasiswa202457201050;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author binak
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        lbAloomni = new javax.swing.JLabel();
        lbFotopelajar = new javax.swing.JLabel();
        pn_dashboard = new javax.swing.JPanel();
        btn_Dashboard = new javax.swing.JLabel();
        lb_Dashboard = new javax.swing.JLabel();
        pn_jurusan = new javax.swing.JPanel();
        btn_Jurusan = new javax.swing.JLabel();
        lb_Jurusan = new javax.swing.JLabel();
        pn_guru = new javax.swing.JPanel();
        btn_guru = new javax.swing.JLabel();
        lb_guru = new javax.swing.JLabel();
        pn_kelas = new javax.swing.JPanel();
        btn_kelas = new javax.swing.JLabel();
        lb_kelas = new javax.swing.JLabel();
        pn_siswa = new javax.swing.JPanel();
        btn_siswa = new javax.swing.JLabel();
        lb_siswa = new javax.swing.JLabel();
        pn_about = new javax.swing.JPanel();
        btn_about = new javax.swing.JLabel();
        lb_about = new javax.swing.JLabel();
        pn_logout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        lb_logout = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_atas = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(0, 153, 204));
        pn_kiri.setPreferredSize(new java.awt.Dimension(220, 542));

        lbAloomni.setBackground(new java.awt.Color(255, 255, 255));
        lbAloomni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbAloomni.setForeground(new java.awt.Color(255, 255, 255));
        lbAloomni.setText("Aloomni");

        lbFotopelajar.setForeground(new java.awt.Color(255, 255, 255));
        lbFotopelajar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-student-50.png"))); // NOI18N

        pn_dashboard.setBackground(new java.awt.Color(0, 153, 204));

        btn_Dashboard.setBackground(new java.awt.Color(0, 153, 204));
        btn_Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dashboard.setText("Dashboard");
        btn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseExited(evt);
            }
        });

        lb_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-dashboard-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_dashboardLayout = new javax.swing.GroupLayout(pn_dashboard);
        pn_dashboard.setLayout(pn_dashboardLayout);
        pn_dashboardLayout.setHorizontalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Dashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dashboardLayout.setVerticalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_jurusan.setBackground(new java.awt.Color(0, 153, 204));

        btn_Jurusan.setBackground(new java.awt.Color(0, 153, 204));
        btn_Jurusan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Jurusan.setForeground(new java.awt.Color(255, 255, 255));
        btn_Jurusan.setText("Jurusan");
        btn_Jurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_JurusanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_JurusanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_JurusanMouseExited(evt);
            }
        });

        lb_Jurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-school-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_jurusanLayout = new javax.swing.GroupLayout(pn_jurusan);
        pn_jurusan.setLayout(pn_jurusanLayout);
        pn_jurusanLayout.setHorizontalGroup(
            pn_jurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_jurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Jurusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_jurusanLayout.setVerticalGroup(
            pn_jurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_Jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_Jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_guru.setBackground(new java.awt.Color(0, 153, 204));

        btn_guru.setBackground(new java.awt.Color(0, 153, 204));
        btn_guru.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_guru.setForeground(new java.awt.Color(255, 255, 255));
        btn_guru.setText("Guru");
        btn_guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_guruMouseExited(evt);
            }
        });

        lb_guru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-teacher-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_guruLayout = new javax.swing.GroupLayout(pn_guru);
        pn_guru.setLayout(pn_guruLayout);
        pn_guruLayout.setHorizontalGroup(
            pn_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_guruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_guru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_guruLayout.setVerticalGroup(
            pn_guruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_guru, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_guru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_kelas.setBackground(new java.awt.Color(0, 153, 204));

        btn_kelas.setBackground(new java.awt.Color(0, 153, 204));
        btn_kelas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_kelas.setForeground(new java.awt.Color(255, 255, 255));
        btn_kelas.setText("Kelas");
        btn_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_kelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_kelasMouseExited(evt);
            }
        });

        lb_kelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-class-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_kelasLayout = new javax.swing.GroupLayout(pn_kelas);
        pn_kelas.setLayout(pn_kelasLayout);
        pn_kelasLayout.setHorizontalGroup(
            pn_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_kelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_kelasLayout.setVerticalGroup(
            pn_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_siswa.setBackground(new java.awt.Color(0, 153, 204));

        btn_siswa.setBackground(new java.awt.Color(0, 153, 204));
        btn_siswa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_siswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_siswa.setText("Siswa");
        btn_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_siswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_siswaMouseExited(evt);
            }
        });

        lb_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-siswa-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_siswaLayout = new javax.swing.GroupLayout(pn_siswa);
        pn_siswa.setLayout(pn_siswaLayout);
        pn_siswaLayout.setHorizontalGroup(
            pn_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_siswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_siswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_siswaLayout.setVerticalGroup(
            pn_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_siswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_about.setBackground(new java.awt.Color(0, 153, 204));

        btn_about.setBackground(new java.awt.Color(0, 153, 204));
        btn_about.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_about.setForeground(new java.awt.Color(255, 255, 255));
        btn_about.setText("About");
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aboutMouseExited(evt);
            }
        });

        lb_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-about-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_aboutLayout = new javax.swing.GroupLayout(pn_about);
        pn_about.setLayout(pn_aboutLayout);
        pn_aboutLayout.setHorizontalGroup(
            pn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_about)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_aboutLayout.setVerticalGroup(
            pn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_about, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_logout.setBackground(new java.awt.Color(0, 153, 204));

        btn_logout.setBackground(new java.awt.Color(0, 153, 204));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });

        lb_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-30.png"))); // NOI18N

        javax.swing.GroupLayout pn_logoutLayout = new javax.swing.GroupLayout(pn_logout);
        pn_logout.setLayout(pn_logoutLayout);
        pn_logoutLayout.setHorizontalGroup(
            pn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_logoutLayout.setVerticalGroup(
            pn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_guru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbFotopelajar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAloomni)
                .addGap(0, 40, Short.MAX_VALUE))
            .addComponent(pn_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFotopelajar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAloomni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(pn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_atasLayout = new javax.swing.GroupLayout(pn_atas);
        pn_atas.setLayout(pn_atasLayout);
        pn_atasLayout.setHorizontalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        pn_atasLayout.setVerticalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_atas, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(255, 255, 255));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseEntered
        pn_dashboard.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_DashboardMouseEntered

    private void btn_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseExited
        pn_dashboard.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_DashboardMouseExited

    private void btn_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseClicked
        pn_dashboard.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new Dashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DashboardMouseClicked

    private void btn_JurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_JurusanMouseClicked
        pn_jurusan.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new Jurusan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_JurusanMouseClicked

    private void btn_JurusanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_JurusanMouseEntered
        pn_jurusan.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_JurusanMouseEntered

    private void btn_JurusanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_JurusanMouseExited
        pn_jurusan.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_JurusanMouseExited

    private void btn_guruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guruMouseClicked
        pn_guru.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new Guru());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_guruMouseClicked

    private void btn_guruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guruMouseEntered
        pn_guru.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_guruMouseEntered

    private void btn_guruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guruMouseExited
        pn_guru.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_guruMouseExited

    private void btn_kelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseClicked
        pn_kelas.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new Kelas());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_kelasMouseClicked

    private void btn_kelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseEntered
        pn_kelas.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_kelasMouseEntered

    private void btn_kelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kelasMouseExited
        pn_kelas.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_kelasMouseExited

    private void btn_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseClicked
        pn_siswa.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new Siswa());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_siswaMouseClicked

    private void btn_siswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseEntered
        pn_siswa.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_siswaMouseEntered

    private void btn_siswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siswaMouseExited
        pn_siswa.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_siswaMouseExited

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
        pn_about.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new About());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_aboutMouseClicked

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        pn_about.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseExited
        pn_about.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_aboutMouseExited

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?",
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            // Jika Yes, kembali ke login
            new Login().setVisible(true);
            dispose(); // Menutup jendela saat ini
        } else if (response == JOptionPane.NO_OPTION) {
            // Jika No, kembali ke menu terakhir yang dibuka 
            // Misalnya, membuka kembali JFrame menu terakhir
            this.setVisible(true); // Menampilkan kembali menu yang sedang aktif
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        pn_logout.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        pn_logout.setBackground(new Color(0, 153, 204));
    }//GEN-LAST:event_btn_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Dashboard;
    private javax.swing.JLabel btn_Jurusan;
    private javax.swing.JLabel btn_about;
    private javax.swing.JLabel btn_guru;
    private javax.swing.JLabel btn_kelas;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_siswa;
    private javax.swing.JLabel lbAloomni;
    private javax.swing.JLabel lbFotopelajar;
    private javax.swing.JLabel lb_Dashboard;
    private javax.swing.JLabel lb_Jurusan;
    private javax.swing.JLabel lb_about;
    private javax.swing.JLabel lb_guru;
    private javax.swing.JLabel lb_kelas;
    private javax.swing.JLabel lb_logout;
    private javax.swing.JLabel lb_siswa;
    private javax.swing.JPanel pn_about;
    private javax.swing.JPanel pn_atas;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_dashboard;
    private javax.swing.JPanel pn_guru;
    private javax.swing.JPanel pn_jurusan;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kelas;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_logout;
    private javax.swing.JPanel pn_siswa;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
