/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package datasiswa202457201050;

/**
 *
 * @author binak
 */
public class Siswa extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Siswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dasar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_txtDataJurusan = new javax.swing.JLabel();
        tf_TanggalLahir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_TambahDataSiswa = new javax.swing.JToggleButton();
        btn_UbahDataSiswa = new javax.swing.JToggleButton();
        btn_HapusDataSiswa = new javax.swing.JToggleButton();
        btn_ResetDataSiswa = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Kelas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_NIS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_Kelas = new javax.swing.JComboBox<>();
        tf_HP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_Alamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_TempatLahir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_Nama = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cb_JenisKel = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        pn_dasar.setPreferredSize(new java.awt.Dimension(649, 504));
        pn_dasar.setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        lb_txtDataJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_txtDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        lb_txtDataJurusan.setText("Data Siswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_txtDataJurusan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_txtDataJurusan)
                .addContainerGap())
        );

        tf_TanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TanggalLahirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama ");

        jLabel2.setText("NIS");

        btn_TambahDataSiswa.setBackground(new java.awt.Color(0, 153, 0));
        btn_TambahDataSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_TambahDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_TambahDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-add-20.png"))); // NOI18N
        btn_TambahDataSiswa.setText("Tambah");
        btn_TambahDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahDataSiswaActionPerformed(evt);
            }
        });

        btn_UbahDataSiswa.setBackground(new java.awt.Color(255, 153, 0));
        btn_UbahDataSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_UbahDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_UbahDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-write-20.png"))); // NOI18N
        btn_UbahDataSiswa.setText("Ubah");
        btn_UbahDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahDataSiswaActionPerformed(evt);
            }
        });

        btn_HapusDataSiswa.setBackground(new java.awt.Color(204, 0, 0));
        btn_HapusDataSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_HapusDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_HapusDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-delete-20.png"))); // NOI18N
        btn_HapusDataSiswa.setText("Hapus");
        btn_HapusDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusDataSiswaActionPerformed(evt);
            }
        });

        btn_ResetDataSiswa.setBackground(new java.awt.Color(0, 153, 255));
        btn_ResetDataSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ResetDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_ResetDataSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons-reset-20 .png"))); // NOI18N
        btn_ResetDataSiswa.setText("Reset");
        btn_ResetDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetDataSiswaActionPerformed(evt);
            }
        });

        tb_Kelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_Kelas);

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Kelas");

        tf_NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NISActionPerformed(evt);
            }
        });

        jLabel5.setText("HP");

        cb_Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3" }));
        cb_Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_KelasActionPerformed(evt);
            }
        });

        tf_HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_HPActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat");

        tf_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_AlamatActionPerformed(evt);
            }
        });

        jLabel7.setText("Tempat Lahir");

        tf_TempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TempatLahirActionPerformed(evt);
            }
        });

        jLabel8.setText("Tanggal Lahir");

        tf_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NamaActionPerformed(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Foto");

        cb_JenisKel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cb_JenisKel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addComponent(btn_TambahDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_UbahDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_HapusDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ResetDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_NIS, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(tf_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_TempatLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(tf_TanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(cb_JenisKel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_Alamat)
                                    .addComponent(cb_Kelas, 0, 214, Short.MAX_VALUE)
                                    .addComponent(tf_HP))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dasarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_NIS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_HP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)))
                        .addGap(2, 2, 2)
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(4, 4, 4)
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addComponent(cb_JenisKel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_TempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(2, 2, 2)
                                .addComponent(tf_TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_Alamat)))
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TambahDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UbahDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HapusDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ResetDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(pn_dasar, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tf_TanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TanggalLahirActionPerformed

    private void btn_TambahDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahDataSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TambahDataSiswaActionPerformed

    private void btn_UbahDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahDataSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UbahDataSiswaActionPerformed

    private void btn_HapusDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusDataSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HapusDataSiswaActionPerformed

    private void btn_ResetDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetDataSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ResetDataSiswaActionPerformed

    private void tf_NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NISActionPerformed

    private void cb_KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_KelasActionPerformed

    private void tf_HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_HPActionPerformed

    private void tf_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_AlamatActionPerformed

    private void tf_TempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TempatLahirActionPerformed

    private void tf_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_HapusDataSiswa;
    private javax.swing.JToggleButton btn_ResetDataSiswa;
    private javax.swing.JToggleButton btn_TambahDataSiswa;
    private javax.swing.JToggleButton btn_UbahDataSiswa;
    private javax.swing.JComboBox<String> cb_JenisKel;
    private javax.swing.JComboBox<String> cb_Kelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb_txtDataJurusan;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JTable tb_Kelas;
    private javax.swing.JTextField tf_Alamat;
    private javax.swing.JTextField tf_HP;
    private javax.swing.JTextField tf_NIS;
    private javax.swing.JTextField tf_Nama;
    private javax.swing.JTextField tf_TanggalLahir;
    private javax.swing.JTextField tf_TempatLahir;
    // End of variables declaration//GEN-END:variables
}
